# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chapter 33' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chapter 33
   pod 'Firebase'
end
